// @ts-nocheck
import PDFDocument from 'pdfkit';
import { v4 as uuidv4 } from 'uuid';
import fs from 'fs';

// Define interfaces for the detailed report structure
export interface ComplianceFinding {
  id: string;
  category: string; // e.g., BOLA, BROKEN_AUTH
  severity: 'critical' | 'high' | 'medium' | 'low';
  description: string;
  remediation: string;
  pciRequirementId: string; // e.g., Req 6.2.4
  pciRequirementName: string; // e.g., Prevent unauthorized access
  gdprArticle?: string; // e.g., Article 5(1)(c)
  gdprArticleTitle?: string; // e.g., Data minimisation
  status: 'PASS' | 'FAIL' | 'N/A';
}

export interface ComplianceReport {
  workspaceName: string;
  scanDate: string; // Formatted date string
  overallComplianceScore: number;
  passedRequirementsCount: number;
  totalRequirements: number;
  findings: ComplianceFinding[];
}

export class ComplianceReportingService {
  private primaryColor = '#1d4ed8';
  private greenColor = '#16a34a';
  private amberColor = '#d97706';
  private redColor = '#dc2626';
  private grayColor = '#6b7280';
  private lightGrayBg = '#f9fafb';
  private lightBorder = '#e5e7eb';

  private pciMapping: { [key: string]: { id: string; name: string } } = {
    'BOLA': { id: 'Req 6.2.4', name: 'Prevent unauthorized access' },
    'BROKEN_AUTH': { id: 'Req 8.2.1', name: 'User identification and authentication' },
    'EXCESSIVE_DATA': { id: 'Req 3.3', name: 'Protect stored account data' },
    'RATE_LIMIT': { id: 'Req 6.4', name: 'Protect against automated attacks' },
    'SECURITY_HEADERS': { id: 'Req 6.3.3', name: 'Security patches and updates' },
    'CORS': { id: 'Req 1.3', name: 'Restrict inbound and outbound traffic' },
    'SQL_INJECTION': { id: 'Req 6.2.1', name: 'Protect against common vulnerabilities' },
    'CREDENTIAL_EXPOSURE': { id: 'Req 8.3.1', name: 'Secure authentication credentials' },
  };

  private gdprMapping: { [key: string]: { article: string; title: string } } = {
    'EXCESSIVE_DATA': { article: 'Article 5(1)(c)', title: 'Data minimisation' },
    'CREDENTIAL_EXPOSURE': { article: 'Article 32', title: 'Security of processing' },
    'BROKEN_AUTH': { article: 'Article 25', title: 'Data protection by design' },
    'CORS': { article: 'Article 5(1)(f)', title: 'Integrity and confidentiality' },
  };

  public async generatePDFReport(report: ComplianceReport, outputPath: string): Promise<void> {
    const doc = new PDFDocument({ margin: 50 });
    const stream = fs.createWriteStream(outputPath);
    doc.pipe(stream);

    const reportId = uuidv4();

    // Helper to add page numbers
    const addPageNumbers = () => {
      let pages = doc.bufferedPageRange();
      for (let i = pages.start; i < pages.start + pages.count; i++) {
        doc.switchToPage(i);
        doc.fillColor(this.primaryColor).rect(50, doc.page.height - 55, doc.page.width - 100, 1).fill();
        doc.fillColor(this.grayColor).fontSize(8).text(
          `Generated by DevPulse by Rashi Technologies | devpulse.in`,
          50,
          doc.page.height - 40,
          { align: 'left' }
        );
        doc.fillColor(this.grayColor).fontSize(8).text(
          `Confidential — Page ${i + 1} of ${pages.count}`,
          50,
          doc.page.height - 40,
          { align: 'right' }
        );
      }
    };

    // HEADER SECTION
    doc.fillColor(this.primaryColor).fontSize(24).font('Helvetica-Bold').text('DevPulse', 50, 50);
    doc.fillColor(this.grayColor).fontSize(12).font('Helvetica').text('PCI DSS v4.0.1 Compliance Report', 50, 60, { align: 'right' });
    doc.moveDown(0.5);
    doc.fontSize(10).text(`Workspace: ${report.workspaceName} | Scan Date: ${report.scanDate} | Report ID: ${reportId}`, { align: 'right' });
    doc.moveDown(0.5);
    doc.fillColor(this.primaryColor).rect(50, doc.y, doc.page.width - 100, 1).fill();
    doc.moveDown(2);

    // EXECUTIVE SUMMARY BOX
    const scoreColor = report.overallComplianceScore >= 80 ? this.greenColor : report.overallComplianceScore >= 60 ? this.amberColor : this.redColor;
    doc.rect(50, doc.y, doc.page.width - 100, 80).fill(this.lightGrayBg).stroke(this.lightBorder);
    doc.fillColor(this.grayColor).fontSize(12).font('Helvetica-Bold').text('EXECUTIVE SUMMARY', 70, doc.y + 15);
    doc.fillColor(scoreColor).fontSize(28).font('Helvetica-Bold').text(`Overall Compliance Score: ${report.overallComplianceScore}%`, 70, doc.y + 35);
    doc.fillColor(this.grayColor).fontSize(10).font('Helvetica').text(`${report.passedRequirementsCount} of ${report.totalRequirements} PCI DSS v4.0.1 Requirements Passed`, 70, doc.y + 65);
    doc.moveDown(5);

    // PCI DSS REQUIREMENTS TABLE
    doc.fillColor(this.primaryColor).fontSize(16).font('Helvetica-Bold').text('PCI DSS Requirements Audit', 50, doc.y);
    doc.moveDown();

    const pciTableHeaders = ['Req ID', 'Requirement Name', 'Status', 'DevPulse Finding'];
    const pciColWidths = [70, 200, 60, 180];
    let pciTableY = doc.y;

    // Draw Table Header
    doc.fontSize(10).font('Helvetica-Bold');
    let currentX = 50;
    pciTableHeaders.forEach((header, i) => {
      doc.text(header, currentX, pciTableY);
      currentX += pciColWidths[i];
    });
    doc.moveTo(50, pciTableY + 15).lineTo(doc.page.width - 50, pciTableY + 15).strokeColor(this.lightBorder).stroke();
    doc.moveDown(0.5);

    // Draw Table Rows
    doc.font('Helvetica').fontSize(9);
    report.findings.forEach((finding) => {
      if (doc.y + 30 > doc.page.height - 100) { doc.addPage(); pciTableY = 50; doc.y = pciTableY + 20; }

      const rowBgColor = finding.status === 'PASS' ? '#e6ffe6' : finding.status === 'FAIL' ? '#ffe6e6' : '#f0f0f0';
      doc.fillColor(rowBgColor).rect(50, doc.y, doc.page.width - 100, 20).fill();
      doc.fillColor('#000000');

      doc.text(finding.pciRequirementId, 50, doc.y + 5);
      doc.text(finding.pciRequirementName, 120, doc.y + 5, { width: pciColWidths[1] });
      doc.text(finding.status, 320, doc.y + 5);
      doc.text(finding.description, 380, doc.y + 5, { width: pciColWidths[3] });
      doc.moveDown(1.5);
      doc.moveTo(50, doc.y).lineTo(doc.page.width - 50, doc.y).strokeColor(this.lightBorder).stroke();
    });
    doc.moveDown(2);

    // GDPR MAPPING SECTION
    doc.addPage();
    doc.fillColor(this.primaryColor).fontSize(16).font('Helvetica-Bold').text('GDPR Article Cross-Reference', 50, doc.y);
    doc.moveDown();

    const gdprTableHeaders = ['Finding Category', 'GDPR Article', 'Article Title'];
    const gdprColWidths = [150, 100, 250];
    let gdprTableY = doc.y;

    // Draw Table Header
    doc.fontSize(10).font('Helvetica-Bold');
    let currentX = 50;
    gdprTableHeaders.forEach((header, i) => {
      doc.text(header, currentX, gdprTableY);
      currentX += gdprColWidths[i];
    });
    doc.moveTo(50, gdprTableY + 15).lineTo(doc.page.width - 50, gdprTableY + 15).strokeColor(this.lightBorder).stroke();
    doc.moveDown(0.5);

    // Draw Table Rows
    doc.font('Helvetica').fontSize(9);
    const gdprFindings = report.findings.filter(f => f.gdprArticle);
    gdprFindings.forEach((finding) => {
      if (doc.y + 30 > doc.page.height - 100) { doc.addPage(); gdprTableY = 50; doc.y = gdprTableY + 20; }

      doc.text(finding.category, 50, doc.y + 5);
      doc.text(finding.gdprArticle!, 200, doc.y + 5);
      doc.text(finding.gdprArticleTitle!, 300, doc.y + 5, { width: gdprColWidths[2] });
      doc.moveDown(1.5);
      doc.moveTo(50, doc.y).lineTo(doc.page.width - 50, doc.y).strokeColor(this.lightBorder).stroke();
    });
    doc.moveDown(2);

    // DETAILED FINDINGS SECTION
    doc.addPage();
    doc.fillColor(this.primaryColor).fontSize(16).font('Helvetica-Bold').text('Detailed Security Findings', 50, doc.y);
    doc.moveDown();

    report.findings.forEach((finding, index) => {
      if (doc.y + 100 > doc.page.height - 100) { doc.addPage(); }

      doc.fillColor(this.grayColor).fontSize(10).font('Helvetica-Bold').text(`FINDING ${index + 1}: ${finding.id}`, 50, doc.y);
      doc.moveDown(0.2);

      const severityColor = finding.severity === 'critical' ? this.redColor : finding.severity === 'high' ? this.amberColor : finding.severity === 'medium' ? this.grayColor : this.greenColor;
      doc.fillColor(severityColor).fontSize(9).font('Helvetica-Bold').text(`Severity: ${finding.severity.toUpperCase()}`, 50, doc.y);
      doc.fillColor('#000000').font('Helvetica').text(`PCI DSS Req: ${finding.pciRequirementId} - ${finding.pciRequirementName}`, 200, doc.y, { width: 200 });
      if (finding.gdprArticle) {
        doc.text(`GDPR Article: ${finding.gdprArticle} - ${finding.gdprArticleTitle}`, 400, doc.y, { width: 150 });
      }
      doc.moveDown(0.5);

      doc.font('Helvetica-Bold').text('Description:', 50, doc.y);
      doc.font('Helvetica').text(finding.description, 120, doc.y, { width: doc.page.width - 170 });
      doc.moveDown(0.5);

      doc.font('Helvetica-Bold').text('Remediation:', 50, doc.y);
      doc.font('Helvetica').text(finding.remediation, 120, doc.y, { width: doc.page.width - 170 });
      doc.moveDown(1.5);
    });

    // QSA DIGITAL SIGNATURE PLACEHOLDER (last page)
    doc.addPage();
    doc.fillColor(this.primaryColor).rect(50, doc.y, doc.page.width - 100, 1).fill();
    doc.moveDown(2);
    doc.fillColor(this.grayColor).fontSize(14).font('Helvetica-Bold').text('Qualified Security Assessor (QSA) Digital Signature', 50, doc.y);
    doc.moveDown();

    doc.rect(50, doc.y, 300, 150).dash(5, { space: 5 }).stroke(this.lightBorder);
    doc.fillColor('#000000').fontSize(10).font('Helvetica').text('Name:', 60, doc.y + 10);
    doc.text('Organization:', 60, doc.y + 40);
    doc.text('QSA Number:', 60, doc.y + 70);
    doc.text('Date:', 60, doc.y + 100);
    doc.text('Signature:', 60, doc.y + 130);
    doc.moveDown(10);

    doc.fontSize(8).fillColor(this.grayColor).text('Note: This report was generated automatically by DevPulse. Manual QSA review required for official PCI DSS certification.', 50, doc.y);

    addPageNumbers(); // Add page numbers to all pages
    doc.end();
  }
}

export const complianceReporting = new ComplianceReportingService();
